language: rust
rust:
    - stable
    - beta
    - nightly

matrix:
  allow_failures:
    - rust: nightly

jdk:
  - oraclejdk8

env:
  global:
    - JAVA_HOME=/usr/lib/jvm/java-8-oracle
    - LD_LIBRARY_PATH=$JAVA_HOME/jre/lib/amd64/server

before_script:
  - export RUST_BACKTRACE=1
  - echo $JAVA_HOME
  - echo $LD_LIBRARY_PATH

script:
  # Build all Rust artefacts
  - cargo build --all
  - cargo test --features=backtrace,invocation
  # Run Java ITs
  - mvn verify
  # Build and run the example project
  - cd example
  - make java_run
