language: rust
rust:
  - stable
  - beta
  - nightly

jdk:
  - openjdk11

matrix:
  include:
    - name: "OracleJDK 8/stable Rust"
      rust: stable
      jdk: oraclejdk8
  allow_failures:
    - rust: nightly

before_script:
  - export RUST_BACKTRACE=1

script:
  - . build_profile
  - cargo build
  - cargo test --features=backtrace,invocation
